---
## ---------------------------------------------------------------------------------------------------------------------
## Preflight tasks
## ---------------------------------------------------------------------------------------------------------------------
- name: Preflight checks
  block:
    - name: Check that the headscale binary file exists in the install dir
      become: true
      ansible.builtin.stat:
        path: "{{ headscale_install_dir }}/headscale_{{ headscale_version }}"
      register: __headscale_binary_file_stat_result

    - name: Check that the headscale systemd unit file exists
      become: true
      ansible.builtin.stat:
        path: "{{ headscale_systemd_unit_file }}"
      register: __systemd_unit_file_stat_result

    - name: Set facts about binary and SystemD files exist
      ansible.builtin.set_fact:
        headscale_binary_file_is_exist: "{{ __headscale_binary_file_stat_result.stat.exists }}"
        headscale_systemd_unit_file_is_exist: "{{ __systemd_unit_file_stat_result.stat.exists }}"
